name: Build and deploy Node.js app to Heroku

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: 'Create env file'
        run: |
          touch .env
          echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
          echo DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} >> .env
          echo DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }} >> .env
          echo NOTION_SECRET_KEY=${{ secrets.NOTION_SECRET_KEY }} >> .env
          echo NOTION_DATABASE_ID=${{ secrets.NOTION_DATABASE_ID }} >> .env
          cat .env

      - name: Install dependencies and BUILD
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

      - name: Build, Push and Release a Docker container to Heroku.
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true